from __future__ import annotations

from typing import Protocol


class StorageService(Protocol):
    async def put_text(self, key: str, content: str) -> str: ...
    async def put_bytes(self, key: str, content: bytes) -> str: ...
    async def get_text(self, key: str) -> str: ...
    async def get_bytes(self, key: str) -> bytes: ...
