from __future__ import annotations

from typing import Protocol
from uuid import UUID


class InvoiceRepository(Protocol):
    async def create_draft(self, payload: dict) -> dict: ...
    async def list_by_tenant(self, tenant_id: UUID) -> list[dict]: ...
    async def get_by_id(self, tenant_id: UUID, invoice_id: UUID) -> dict | None: ...
    async def update_status(self, tenant_id: UUID, invoice_id: UUID, status: str) -> None: ...
    async def update_issue_payload(self, tenant_id: UUID, invoice_id: UUID, payload: dict) -> None: ...
    async def find_by_idempotency_key(self, tenant_id: UUID, key: str) -> dict | None: ...
