FROM python:3.12-slim
WORKDIR /app
COPY pyproject.toml README.md ./
RUN pip install --no-cache-dir .
COPY app ./app
COPY migrations ./migrations
COPY alembic.ini ./alembic.ini
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
